import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F5F7F9",
  },
  header: {
    height: 56,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#5CB15A",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  headerTitle: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "700",
  },
  content: {
    padding: 20,
    alignItems: "center",
  },
  instruction: {
    fontSize: 15,
    color: "#4B5563",
    textAlign: "center",
    marginBottom: 24,
    marginTop: 10,
    lineHeight: 22,
  },
  qrContainer: {
    backgroundColor: "#FFF",
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
    marginBottom: 24,
    width: "100%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  qrImage: {
    width: "100%",
    height: "100%",
  },
  infoCard: {
    backgroundColor: "#FFF",
    width: "100%",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "500",
  },
  infoAmount: {
    fontSize: 18,
    color: "#5CB15A",
    fontWeight: "700",
  },
  infoContent: {
    fontSize: 16,
    color: "#1E1E1E",
    fontWeight: "700",
  },
  warningText: {
    fontSize: 12,
    color: "#DC2626",
    fontStyle: "italic",
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingTop: 12,
  },
  completeBtn: {
    backgroundColor: "#5CB15A",
    width: "100%",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 24,
  },
  completeBtnText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "700",
  },
  countdownContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7ED",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#FDE68A",
    gap: 8,
  },
  countdownText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#F59E0B",
  },
  countdownDanger: {
    color: "#DC2626",
  },
});
