import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F3F4F6",
  },
  container: {
    padding: 12,
    paddingBottom: 40,
  },
  containerNoPadTop: {
    padding: 12,
    paddingTop: 0,
    paddingBottom: 40,
  },
  header: {
    backgroundColor: "#5CB15A",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: "#5CB15A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    marginHorizontal: 12,
    marginTop: 12,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#FFF",
  },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  searchInput: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    fontSize: 14,
    color: "#111827",
  },
  filterRow: {
    marginTop: 12,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    marginRight: 8,
    backgroundColor: "#FFFFFF",
  },
  filterChipActive: {
    borderColor: "#5CB15A",
    backgroundColor: "#ECFDF5",
  },
  filterChipText: {
    fontSize: 12,
    color: "#374151",
    fontWeight: "600",
  },
  filterChipTextActive: {
    color: "#047857",
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 16,
  },
  bookingCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 0,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  infoLabel: {
    width: "25%",
    fontSize: 14,
    fontWeight: "500",
    color: "#6B7280",
  },
  infoValue: {
    width: "75%",
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  statusBadgeContainer: {
    flex: 1,
    alignItems: "flex-start",
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  statusPending: {
    backgroundColor: "#E5E7EB",
  },
  statusConfirmed: {
    backgroundColor: "#DBEAFE",
  },
  statusCompleted: {
    backgroundColor: "#DCFCE7",
  },
  statusCancelled: {
    backgroundColor: "#FEE2E2",
  },
  statusCancelRequested: {
    backgroundColor: "#FEF3C7",
  },
  actionRow: {
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 10,
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  actionButtonWrap: {
    borderWidth: 0,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#F3F4F6",
  },
  actionButtonText: {
    fontSize: 13,
    color: "#111827",
    fontWeight: "600",
  },
  confirmBtn: {
    backgroundColor: "#DBEAFE",
  },
  completeBtn: {
    backgroundColor: "#DCFCE7",
  },
  cancelBtn: {
    backgroundColor: "#FEE2E2",
  },
  stateText: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    marginVertical: 8,
  },
  cancelReasonContainer: {
    marginTop: 8,
    padding: 12,
    backgroundColor: "#FEF2F2",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  cancelReasonTitle: {
    color: "#DC2626",
    fontWeight: "bold",
    fontSize: 16,
  },
  cancelReasonText: {
    color: "#DC2626",
    marginTop: 4,
  },
  tagsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 12,
  },
  tag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  tagText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#374151",
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    width: "100%",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    gap: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    textAlign: "center",
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: "#111827",
    minHeight: 100,
    textAlignVertical: "top",
    marginBottom: 20,
    backgroundColor: "#F9FAFB",
  },
  modalButtons: {
    flexDirection: "row",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  modalButtonCancel: {
    backgroundColor: "#F3F4F6",
  },
  modalButtonConfirm: {
    backgroundColor: "#DC2626",
  },
  modalButtonCancelText: {
    color: "#374151",
    fontWeight: "bold",
  },
  modalButtonConfirmText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  actionTextBlue: {
    color: "#2563EB",
  },
  actionTextRed: {
    color: "#DC2626",
  },
  actionTextGreen: {
    color: "#16A34A",
  },
});
