import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F3F4F6",
  },
  container: {
    padding: 12,
    paddingBottom: 40,
  },
  header: {
    backgroundColor: "#5CB15A",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: "#5CB15A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    marginHorizontal: 12,
    marginTop: 12,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#FFF",
  },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  bookingCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 0,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  divider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 12,
  },
  sectionTitle: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#111827",
    marginBottom: 8,
  },
  serviceItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderColor: "#F3F4F6",
  },
  serviceInfo: {
    flex: 1,
  },
  serviceName: {
    color: "#374151",
  },
  serviceSubtotal: {
    color: "#111827",
    fontWeight: "600",
  },
  serviceNameText: {
    fontWeight: "600",
    color: "#111827",
  },
  addonBadge: {
    backgroundColor: "#FEF3C7",
    alignSelf: "flex-start",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 2,
  },
  addonBadgeText: {
    color: "#D97706",
    fontSize: 10,
    fontWeight: "bold",
  },
  addServiceBtn: {
    alignSelf: "center",
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#F0FDF4",
    borderColor: "#5CB15A",
    borderWidth: 1,
    borderRadius: 8,
  },
  addServiceBtnText: {
    color: "#16A34A",
    fontWeight: "bold",
    fontSize: 14,
  },
  cancelReasonContainer: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#FEF2F2",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  cancelReasonTitle: {
    color: "#DC2626",
    fontWeight: "bold",
    fontSize: 16,
  },
  cancelReasonText: {
    color: "#DC2626",
    marginTop: 4,
  },
  staffRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  staffName: {
    fontWeight: "bold",
    color: "#111827",
    fontSize: 14,
  },
  assignBtn: {
    backgroundColor: "#E0E7FF",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  assignBtnText: {
    color: "#4338CA",
    fontWeight: "bold",
    fontSize: 11,
  },
  bottomBar: {
    padding: 16,
    backgroundColor: "#FFF",
    borderTopWidth: 1,
    borderColor: "#E5E7EB",
  },
  actionButtonsRow: {
    flexDirection: "row",
    gap: 12,
  },
  actionButton: {
    flex: 1,
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  confirmActionBtn: {
    backgroundColor: "#DBEAFE",
  },
  cancelActionBtn: {
    backgroundColor: "#FEE2E2",
  },
  completeActionBtn: {
    backgroundColor: "#5CB15A",
  },
  confirmActionText: {
    color: "#2563EB",
    fontWeight: "bold",
  },
  cancelActionText: {
    color: "#DC2626",
    fontWeight: "bold",
  },
  completeActionText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  // Modal extra styles
  staffItem: {
    padding: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    marginBottom: 8,
  },
  staffItemSelected: {
    borderColor: "#5CB15A",
    backgroundColor: "#F0FDF4",
  },
  staffItemBusy: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FCA5A5",
  },
  staffHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  staffNameText: {
    fontWeight: "bold",
    color: "#111827",
    fontSize: 16,
  },
  busyBadge: {
    backgroundColor: "#FEE2E2",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  freeBadge: {
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  busyBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#DC2626",
  },
  freeBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#16A34A",
  },
  staffSubtext: {
    color: "#6B7280",
    fontSize: 14,
  },
  busyText: {
    color: "#DC2626",
    fontSize: 12,
    marginTop: 4,
  },
  scheduleText: {
    color: "#6B7280",
    fontSize: 12,
    marginTop: 2,
  },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  searchBarInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    fontSize: 14,
    color: "#111827",
  },
  serviceSelectRow: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  serviceSelectRowSelected: {
    borderColor: "#5CB15A",
    backgroundColor: "#F0FDF4",
  },
  quantitySelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  quantityBtn: {
    padding: 6,
  },
  quantityText: {
    paddingHorizontal: 8,
    fontSize: 14,
    fontWeight: "bold",
    color: "#111827",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  infoLabel: {
    width: "30%",
    fontSize: 14,
    fontWeight: "500",
    color: "#6B7280",
  },
  infoValue: {
    width: "70%",
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  statusPending: {
    backgroundColor: "#E5E7EB",
  },
  statusConfirmed: {
    backgroundColor: "#DBEAFE",
  },
  statusCompleted: {
    backgroundColor: "#DCFCE7",
  },
  statusCancelled: {
    backgroundColor: "#FEE2E2",
  },
  statusCancelRequested: {
    backgroundColor: "#FEF3C7",
  },
  stateText: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    marginVertical: 8,
  },
  tagsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 12,
  },
  tag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  tagText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#374151",
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    width: "100%",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    gap: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    textAlign: "center",
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: "#111827",
    minHeight: 100,
    textAlignVertical: "top",
    marginBottom: 20,
    backgroundColor: "#F9FAFB",
  },
  modalButtons: {
    flexDirection: "row",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  modalButtonCancel: {
    backgroundColor: "#F3F4F6",
  },
  modalButtonConfirm: {
    backgroundColor: "#DC2626",
  },
  modalButtonCancelText: {
    color: "#374151",
    fontWeight: "bold",
  },
  modalButtonConfirmText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  statusBadgeContainer: {
    flex: 1,
    alignItems: "flex-start",
  },
  modalTitleMb12: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    textAlign: "center",
    marginBottom: 12,
  },
  staffListScroll: {
    maxHeight: 400,
    marginBottom: 16,
  },
  serviceListScroll: {
    maxHeight: 400,
    marginBottom: 12,
  },
  serviceItemMargin: {
    marginBottom: 8,
  },
  modalButtonGreen: {
    backgroundColor: "#5CB15A",
  },
  modalButtonWhiteText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  totalPriceTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: "#16A34A",
    flex: 1,
  },
  totalPriceText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#16A34A",
  },
  modalSectionLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 8,
    marginTop: 8,
  },
});
